# -*- coding: utf-8 -*-
"""Support_Vector_Machine_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qcprjMvAfdNo2fy2cLENw-MDsWwGB-nd
"""

import io
import pandas as pd
from google.colab import files

"""# Uploading File"""

from sklearn.datasets import load_wine
wine_data = load_wine(as_frame=True)
X = wine_data.data    
y = wine_data.target 

wine_df = wine_data.frame

print(wine_df)

"""Essential Pandas Commands to inspect files"""

wine_df.info()

wine_df.describe()

wine_df.isnull().sum()

"""Split train and test data"""

X = wine_df.drop('target', axis = 1)
y = wine_df['target']

from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

"""Scaling data"""

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""# SVC Linear Model"""

model = SVC(kernel = 'linear')
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

"""# SVC RBF Model"""

model1 = SVC(kernel = 'rbf')
model1.fit(X_train, y_train)

y_pred = model1.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

"""# SVC Poly Model"""

model2 = SVC(kernel = 'poly')
model2.fit(X_train, y_train)

y_pred = model2.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

"""# SVC Sigmoid Model"""

model3 = SVC(kernel = 'sigmoid')
model3.fit(X_train, y_train)

y_pred = model2.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))